# Generated by Django 4.2.11 on 2024-07-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Email", models.EmailField(max_length=254, unique=True)),
                ("Password", models.CharField(max_length=128)),
                ("FName", models.CharField(max_length=50)),
                ("LName", models.CharField(max_length=50)),
                ("Cellphone", models.CharField(max_length=20)),
                ("IsActive", models.BooleanField(default=True)),
                ("IsStaff", models.BooleanField(default=False)),
                ("IsSuperuser", models.BooleanField(default=False)),
                ("LastLogin", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
