# Generated by Django 4.2.11 on 2024-07-14 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Auth", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="User", new_name="Account",),
    ]
